### PR TITLE
Add source diagram for Commit Version

### PR DESCRIPTION
**Pull request by jordanmccullough**
Another diagram as a separate Illustrator resource file for deriving PNG, JPG, or SVG artifacts.

### CODE REVIEW

**Comment by brntbeer** [comment]
Maybe im off, but can you just post an image of this?

**Comment by jordanmccullough** [comment]
screen shot 2013-11-27 at 11 43 32 am

**Comment by brntbeer** [comment]
I'm confused, thought this already exists?

**Comment by jordanmccullough** [comment]
This is the diagram source Adobe Illustrator file. The actual PNGs and the slide additions to the Foundations deck have already been merged in.

**Comment by brntbeer** [comment]
oh. why bother with the AI file then? i mean whatever just merge it if it
looks the same. no need to really ask about that. haha

On Wed, Nov 27, 2013 at 11:46 AM, Jordan McCullough <
notifications@github.com> wrote:

> This is the diagram source Adobe Illustrator file. The actual PNGs and the
> slide additions to the Foundations deck have already been merged in.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/github/teach.github.com/pull/241#issuecomment-29409505
> .

## 

Brent Beer
GitHub Training
http://training.github.com
https://github.com/brntbeer

**Comment by jordanmccullough** [comment]
Good point, just going with the typical procedure to merge in. Should've included it in the original PR for sure. :ship:ing now!

**Pull request merged**
