### PR TITLE
Revising slide content, notes, titles

### PR DESCRIPTION
**Pull request by jordanmccullough**
Changes are _not_ PR merge-ready as of first commit, but wanted to open up the review and discussion around the slide deck content.

Goals of this PR and the associated changes:
- Improve the language and consistency across slides
- Tidy up redundant content
- Amp-up the presenter notes and align with class notes/outline

Slide deck optional goals:
- Fix basic order of slides to more gradually build knowledge basic for students
- Resolve topics that are ahead of each other (e.g. `git checkout branch` before `git branch`, etc.)

### CODE REVIEW

**Comment by matthewmccullough** [comment]
Look good to you @brntbeer ?

**Comment by brntbeer** [comment]
@matthewmccullough it looks good, but i want to check it out locally before we do anything.

Also, notice he said it's a WIP, not mergeready yet as of first commit ;)

**Comment by jordanmccullough** [comment]
Gents, I haven't pushed additional (and considerable) more improvements. Just wanted to open up the conversation and review process. Let's hold off on merging just yet. Thanks.

**Comment by matthewmccullough** [comment]
I like those wording changes.

**Comment by brntbeer** [comment]
looks good to me! keep up the good work in progress @jordanmccullough!

**Comment by jordanmccullough** [comment]
Closing, approached changes with tidier branch and content cleanup. See https://github.com/github/teach.github.com/pull/112

**Pull request closed without merging**
