### PR TITLE
Copyedit on Private Advanced Git Training at JavaZone

### PR DESCRIPTION
**Pull request by randomecho**
The last commit on this file mentioned it being a first draft, wasn't sure if that meant you had the next draft on hand, hopefully you don't, and so here this is:
- Added "at JavaZone" to help differentiate in listing
- Signed Tags, Bisect could do with a step up to H3
- Forgoing bare URLs for linked words, for web aesthetic
- Bullets in Audience Requirements feels like H2 time
- Last Required bullet point may not be required

### CODE REVIEW

**Comment by jordanmccullough** [comment]
I'll let @matthewmccullough give final approval for his class notes, but @randomecho's edits make the document :sparkles:.

**Comment by matthewmccullough** [comment]
@randomecho always making our work :fireworks:. Awesome tuneups! I even mentioned you in class.

**Comment by randomecho** [comment]
Thanks for the props. Working on documentation of any kind is fun. Was also nice to see this commit not step on your edit toes (assuming).

**Comment by matthewmccullough** [comment]
@randomecho You have now been talked about in a "I can't believe how awesome the helps is!" from the arctic circle in northern Norway. Achievement unlocked! Props to you again.

**Pull request merged**
