### PR TITLE
Markdown standardization

### PR DESCRIPTION
**Pull request by matthewmccullough**
Should we change to these gems?

Give me a quick rundown again of if it has any impacts visually?  Wouldn't the "default" actually be the ones GitHub uses without it specified?  Just asking ALL OF THE QUESTIONS™ :smile: Mr. Ruby (@brntbeer ).

### CODE REVIEW

**Comment by brntbeer** [comment]
Basically use redcarpet because its most active project and probably
renders fastest because vmg wrote it.

I think other projects are built off of it? Like redcloth? I just know its
suggested to use redcarpet

Sent from my phone into space.

On Mar 25, 2013, at 9:17 AM, Matthew McCullough notifications@github.com
wrote:

Should we change to these gems?

Give me a quick rundown again of if it has any impacts visually? Wouldn't
the "default" actually be the ones GitHub uses without it specified? Just
asking ALL OF THE QUESTIONS™ [image: :smile:] Mr. Ruby

## (@brntbeerhttps://github.com/brntbeer).

You can merge this Pull Request by running

  git pull https://github.com/github/teach.github.com markdown-standardization

Or view, comment on, or merge it at:

  https://github.com/github/teach.github.com/pull/104
Commit Summary
- added rdiscount to gemfile and to cache since it's needed to even run
  jekyll
- added redcloth too

File Changes
- _M_ Gemfilehttps://github.com/github/teach.github.com/pull/104/files#diff-0(2)
- _M_ Gemfile.lockhttps://github.com/github/teach.github.com/pull/104/files#diff-1(4)
- _A_ vendor/cache/RedCloth-4.2.9.gemhttps://github.com/github/teach.github.com/pull/104/files#diff-2(0)
- _A_ vendor/cache/rdiscount-2.0.7.gemhttps://github.com/github/teach.github.com/pull/104/files#diff-3(0)

Patch Links:
- https://github.com/github/teach.github.com/pull/104.patch
- https://github.com/github/teach.github.com/pull/104.diff

**Comment by matthewmccullough** [comment]
@brntbeer These already seem to be the case in `gh-pages` branch if I'm seeing it correctly.  Close this PR then since the work is already merged via some other effort?

**Comment by brntbeer** [comment]
I'll take a look in a few min when I'm in front of a computer. Can't
remember if someone beat me to the punch or not

Sent from my phone into space

On Mar 25, 2013, at 9:26 AM, Matthew McCullough notifications@github.com
wrote:

@brntbeer https://github.com/brntbeer These already seem to be the case
in gh-pages branch if I'm seeing it correctly. Close this PR then since the
work is already merged via some other effort?

—
Reply to this email directly or view it on
GitHubhttps://github.com/github/teach.github.com/pull/104#issuecomment-15403797
.

**Comment by brntbeer** [comment]
Yeah. in this PR i say to use redcloth and rdiscount, however i had been beaten by Ben in https://github.com/github/teach.github.com/pull/80.

Im happy to close this, I'll continue my internal debate on whether or not we should just use redcarpet and not rdiscount/redcloth.

**Comment by matthewmccullough** [comment]
Okay.  Sounds good.  I'll let you close this one since the goodness has been incorporated.

**Pull request closed without merging**
