### PR TITLE
Use screenshot of GitHub YouTube channel when not logged in

### PR DESCRIPTION
**Pull request by randomecho**
Swaps out the screenshot of the GitHub YouTube channel page since current is logged in under an account.

The page looks markedly different now as well after their redo.

Went with _Videos_ instead of the default _Home_ tab, former feels like it would match more. 

Could (should?) have gone with adding in the [GitHubGuides channel](http://www.youtube.com/user/GitHubGuides)

### CODE REVIEW

**Comment by jordanmccullough** [comment]
@randomecho, Thanks for the continued contributions. I'm closing this issue in favor of two PRs, one for each of these changes.

[Screenshot update](https://github.com/github/teach.github.com/pull/189)
[Wikipedia link fix](https://github.com/github/teach.github.com/pull/190)

**Comment by randomecho** [comment]
Cool stuff. The Wikipedia link fix was rather incidental.

**Comment by jordanmccullough** [comment]
Really do appreciate all the changes. Just wanted the two commits to be distinct for history traceability's sake.

**Comment by randomecho** [comment]
Sweeeet. Just didn't want to flood with PRs. Will keep that in mind for future to keep like in like for commit/PR grouping.

**Pull request closed without merging**
