### PR TITLE
Update HydeSlide-Plugins rev, include new Help module JS

### PR DESCRIPTION
**Pull request by jordanmccullough**
With updated HydeSlides-Plugins rev, now including the Help
JavaScript module for RevealJS decks.

### CODE REVIEW

**Comment by jordanmccullough** [comment]
Just press `shift`+`/` (i.e. `?`) for the new Help panel:
screen shot 2013-06-02 at 5 25 14 pm

**Comment by brntbeer** [comment]
So hot

On Sunday, June 2, 2013, Jordan McCullough wrote:

> Just press shift+/ (i.e. ?) for the new Help panel:
> [image: screen shot 2013-06-02 at 5 25 14 pm]https://f.cloud.github.com/assets/352082/597094/b0f05384-cbdb-11e2-947b-ee1a8107f40b.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/github/teach.github.com/pull/162#issuecomment-18816260
> .

## 

Brent Beer
GitHub:Training
http://training.github.com
https://github.com/brntbeer

**Comment by matthewmccullough** [comment]
I tested it locally and it worked like a champ.  I again remembered to totally purge cache so this should be good to merge! :ship:

**Comment by matthewmccullough** [comment]
Oh wait.  "setp" should be "step" on the help screen.

**Comment by jordanmccullough** [comment]
Fixed. Merge at will!

**Comment by jordanmccullough** [comment]
screen shot 2013-06-02 at 6 55 54 pm

**Pull request merged**
