### PR TITLE
start collection of classroom materials

### PR DESCRIPTION
**Pull request by brntbeer**
title says it all.

cc @github/training-team and @github/education @jlord

### CODE REVIEW

**Comment by jordanmccullough** [comment]
:cool:. I like seeing educational web sites directly referencing Git and GitHub content. Let's do this.

**Comment by izuzak** [comment]
I :heart: this! Let's do it! 

What kinds of sites are we looking to collect here? @jlord put together a :cool:  [list of educators using GitHub](https://github.com/jlord/edu-on-github) and there are all kinds of sites linked there (which I love):
- GitHub repositories with classroom materials
- GitHub Pages sites for courses (like the one Tufts one)
- Educational JavaScript Web applications used in courses and hosted on GitHub Pages
- GitHub organizations for specific courses or whole departments/universities
- ...

**Comment by matthewmccullough** [comment]
I had a long standing TODO in Things.app to talk to @jlord about [all things GitHub in Education, inspired by her Team post](https://team.githubapp.com/statuses/16684). However, @brntbeer really owned that path with his [OSCON talk on "Collaborative Teaching for More Effective Learning"](http://www.oscon.com/oscon2013/public/schedule/speaker/152215) and would love to step aside and let him PRP that category of passion w.r.t. how it applies to training and presentations.  I can't tell you how excited I am to see this conversation rekindled with your passion for the same topic, @izuzak!

**Comment by matthewmccullough** [comment]
Also, I don't want this to in any way grab or overlap with efforts that @github/education already has underway, so just pinging to make sure we are all coordinated and putting this data in the right place, now that there's a [Edu site underway](https://github.com/github/education.github.com).

**Comment by izuzak** [comment]
@matthewmccullough Yeah, I guess there might be some overlap (everyone loves education! :school: :heart:). That's why I was asking about what kind of sites we were looking to link to on the teach.github.com. 

Anyway, @brntbeer and @github/education -- if you'd like a hand with anything, just let me know. I :heart: :heart: :heart:  GitHub+Edu. I think there's **huge** potential there (not just for GitHub, but for educators and students).

**Comment by brntbeer** [comment]
:+1: thanks!

**Pull request merged**
