### PR TITLE
Add first draft GitHub feature slides

### PR DESCRIPTION
**Pull request by jordanmccullough**
Starting with a WIP to get team review on possible chapters discussing GitHub features and summaries. This is not to copy/duplicate anything in the Help, but to surface features that might be help to integration into custom slide decks or high-level examinations of Git and GitHub integration.

### CODE REVIEW

**Comment by jordanmccullough** [comment]
Basic but important features including Pull Requests, Organizations, Issues, and GH-Pages built out. Several slides also include presenter note content where slides did not particularly fit in.

Screenshots and more refinements would make these slides :sparkles: more, but I feel this is a good start.

**Comment by matthewmccullough** [comment]
@jordanmccullough Would you like me to load this locally later today and give it one voice for a :+1: to ship?

**Comment by jordanmccullough** [comment]
Yep! Please do.

**Comment by matthewmccullough** [comment]
I have ideas for refining these here and there based on some things I am excited to add to them, but they are wonderful for :shipit: right now and then we'll just iterate.  Do it!  We can always tune them. :smile:

**Pull request merged**
