### PR TITLE
Fix Travis build

### PR DESCRIPTION
**Pull request by afeld**
See commits.

/cc @jordanmccullough

### CODE REVIEW

**Comment by jordanmccullough** [comment]
To my :eyes:, this looks good. Let's :shipit:.

**Comment by matthewmccullough** [comment]
It is not fair to have so much awesome @afeld help. So :smile: about all you have already done for us Aiden!

**Comment by afeld** [comment]
:crying_cat_face: :heart_eyes_cat:

**Comment by jordanmccullough** [comment]
In light of this update, anyone care to see why Travis is saying unhappy things about [this PR](https://github.com/github/teach.github.com/pull/214)? Thanks!

**Pull request merged**
