### PR TITLE
Dynamically generate a diagram-only deck

### PR DESCRIPTION
**Pull request by matthewmccullough**
Implementation of a diagram-only deck for some modes of teaching Git.

### CODE REVIEW

**Comment by matthewmccullough** [comment]
CC: @jordanmccullough Help. This doesn't work yet. It doesn't show any slides.

**Comment by jordanmccullough** [comment]
On it.

**Comment by jordanmccullough** [comment]
- Force-pushed to clean up history and issues introduced in a few commits. 
- Resolving final tweak to ensure template does not include empty or title-only chapters. (See screenshot)

screen shot 2013-10-08 at 12 36 26 pm

**Comment by matthewmccullough** [comment]
Really excited about this.  CCing @johndbritton and @afeld as this might support a usage pattern I've heard them mention of wanting a visuals-only deck.  Now it will be auto-generated!

**Comment by matthewmccullough** [comment]
@jordanmccullough This belong on an edit to your [Ship It List for October](https://github.com/github/outreach/discussions/11) perhaps!

**Comment by jordanmccullough** [comment]
Certainly should, @matthewmccullough. This isn't ready for review just yet... final tweaks forthcoming.

**Comment by jordanmccullough** [comment]
Abandoning support for title chapter slides in initial pass due to wonky logic necessary with tag objects and nesting order. Let's ship this first pass and revisit sometime later.

screen shot 2013-10-08 at 5 27 55 pm

**Comment by matthewmccullough** [comment]
:+1:

**Comment by matthewmccullough** [comment]
@jordanmccullough You should write a two-line ship post for this for anyone trying to explain Git, even if they aren't teachers.  Many GitHubbers could benefit.

**Pull request merged**
