### PR TITLE
Add "What is a commit" AI source diagram

### PR DESCRIPTION
**Pull request by jordanmccullough**
Including new source Illustrator file used to build the "What is a Commit" diagram in the Foundations deck.

screen shot 2013-10-10 at 5 29 41 pm

### CODE REVIEW

**Comment by randomecho** [comment]
"Commiter" in box 477B is missing a T

**Comment by jordanmccullough** [comment]
Fixed in the source AI and the PNG in the slides.

screen shot 2013-10-10 at 6 23 57 pm

**Comment by jordanmccullough** [comment]
@randomecho Thanks as always for the :eyes: on the details!

**Comment by tlberglund** [comment]
@jordanmccullough Is this good to go? :)

**Comment by jordanmccullough** [comment]
Yes. :shipit:

**Comment by matthewmccullough** [comment]
@jordanmccullough Merge it! :heart:

**Pull request merged**
