### PR TITLE
Resolve GitHub slide deck theme and diagram issues

### PR DESCRIPTION
**Pull request by jordanmccullough**
## TODO
- [x] Fix default font size
- [x] Fix code block font size
- [ ] ~~Adjust diagram scaling (small resolution/screens)~~

### CODE REVIEW

**Comment by jordanmccullough** [comment]
Punting on the diagram scaling issue, which needs some further work and tweaks with the way the build-outs are handled.

For now, let's integrate the font and pre block sizing for immediate improvement.

@brntbeer, @tlberglund, or @matthewmccullough, Give this one last :eyes: to make sure it checks out. It's merge-ready.

**Comment by matthewmccullough** [comment]
Checking it out right now locally.

**Comment by matthewmccullough** [comment]
@jordanmccullough I force pushed a rebased copy of this branch for your consideration.

**Comment by jordanmccullough** [comment]
:shipit:

**Pull request merged**
