### PR TITLE
Relocated all Foundataion chapter content under respective folder

### PR DESCRIPTION
**Pull request by jordanmccullough**
Tagging and slide-deck building remains the same. This improves
human-readable strcuture of slides/chapters available.

### CODE REVIEW

**Comment by jordanmccullough** [comment]
After chatting with @matthewmccullough, this may be an over-organized way of grouping the slide chapters. While this improves a quick survey of the "big picture" segments, it does pose the potential for us duplicating overlooked chapters when they're nested.

Just getting this idea out there. If it's not :100: :+1: with the team, let's just close this.

**Comment by matthewmccullough** [comment]
@jordanmccullough I'm generally :+1: on this, but wouldn't some of them go into an "intro" folder adjacent to the "Foundations" folder that are just branding and generic "Welcome to class" slides and closing slides?

**Comment by brntbeer** [comment]
I'm for it. it sucks that it had to happen and be moved, but i like this move a lot more. makes it easier to isolate other presentations.

And a related question, can we change the path in the front-matter of a chapter setting to grab files under a different presentation (if i was doing a talk to academia i need most of foundations, but i'll have some stuff from `academia/` as well)

**Comment by jordanmccullough** [comment]
@matthewmccullough Regarding...

> wouldn't some of them go into an "intro" folder adjacent to the "Foundations" folder

Most certainly. Let me get that into the PR of this branch.

**Comment by jordanmccullough** [comment]
Oops! Let me clean this up. Accidentally introduced a rebase and drug in commits we don't want in here. Sorry about that.

**Comment by matthewmccullough** [comment]
@jordanmccullough Good to go now?

**Comment by jordanmccullough** [comment]
Sorry about the inclusion of the other two files (due to rebase) but they were already on gh-pages, so, no harm.

**Pull request merged**
