### PR TITLE
Adding page for additional materials as dicussed in #147

### PR DESCRIPTION
**Pull request by gurugray**

### CODE REVIEW

**Comment by matthewmccullough** [comment]
Looks good to me for a first :ship:. Let's get one other pair of @github/training-team eyes on it.

**Comment by randomecho** [comment]
"a simple tool for demonstration of git history working." sounds a bit clunky. How about something like 

> a simple tool to demonstrate how Git history works.

**Comment by gurugray** [comment]
@randomecho thanks :) — fixed.

**Comment by gurugray** [comment]
any other improvements? :)

**Comment by brntbeer** [comment]
Thanks @gurugray! I will be looking at this a bit later today. Love the addition

**Comment by gurugray** [comment]
@brntbeer good, thanks for that!

**Pull request merged**
