### PR TITLE
Foundations Slide Deck Updates for Custom ILT

### PR DESCRIPTION
**Pull request by jordanmccullough**
@brntbeer I've revised the structure of the chapters to be more in line with the outline in github/trainingteam. The chapter content has been updated to address typos, clarified examples, and trimmed down speaker notes and commented-out cruft.

### CODE REVIEW

**Comment by jordanmccullough** [comment]
This may not be something we want to entirely merge in, but I wanted to open up the conversation here. Adjustments to core git-foundations.html slide deck should follow.

**Comment by jordanmccullough** [comment]
:+1: Good suggestion. I like the abstraction away from specific instructors (so the chapter content is usable by all). Great catch.

**Comment by jordanmccullough** [comment]
Name abstraction done. 98e60f5

**Comment by matthewmccullough** [comment]
Looks like it has had @brntbeer eyes and mine now. Let's make this happen!

**Pull request merged**
