### PR TITLE
Add GitHub logo to preroll slide

### PR DESCRIPTION
**Pull request by jordanmccullough**
Eliminating the ambiguity of the opening slide that previously only contains chat room placeholder and Training Team links.

Styling and theming need more attention, but this gets the first step of including GitHub branding in the markdown.

screen shot 2013-05-21 at 11 10 14 am

### CODE REVIEW

**Comment by matthewmccullough** [comment]
Just noticed this shortcoming today as students filed into the room and asked which class it was. :+1: on reading my mind on the cure!

**Comment by brntbeer** [comment]
Just playing devil's advocate here, but our primary content is JUST Git. =\ 

screen shot 2013-05-21 at 10 41 23 am

Also, while im thinking about it, Git should be capitalized i think

**Comment by brntbeer** [comment]
Well, rather, I meant if we say "Git and GitHub" we should maybe not use the official Git logo, but just the word. i was just playing around with how it'd look on the preroll

**Comment by jordanmccullough** [comment]
@brntbeer, Great suggestion. How about this...

screen shot 2013-05-21 at 12 21 43 pm

**Comment by brntbeer** [comment]
I'm okay with this. Only slight additional concern is Blacktocat logo in lower right with Mark on top. possible to ditch the background on preroll slide? If it's a pain, I'm happy to say i dont really care

**Comment by matthewmccullough** [comment]
@brntbeer has a great point about the content of the class being Git-focused, but I'm wondering if it has become [too busy](http://www.youtube.com/watch?v=Wac3aGn5twc) with all the marks.

I'd like to know the team's sentiment of going more and more towards leading solely with the word "GitHub" and almost softening our usage of "Git" as we start to incorporate more of the GitHub flow.

**Comment by tlberglund** [comment]
@matthewmccullough My opinion is that we are in the GitHüb business (limited time Austria-themed spelling), not the Git business.

**Comment by brntbeer** [comment]
Also agreed we are a GitHub bidness

**Comment by jordanmccullough** [comment]
@matthewmccullough and @tlberglund I understand the brand/naming use, please see the first screenshot with the PR using just the GitHub logo. Is that what you are speaking to keeping?

@brntbeer and mentioned that our classes are GitHub and Git focused, so the suggestion to include both logos is valid. However, the awesomeness of the GH logo classed with the "old" Git logo, so I tried text-only [here](https://github.com/github/teach.github.com/pull/149#issuecomment-18227046).

However, if @brntbeer is in agreement, I'd like to fall back to just the GitHub logo first version as well.

**Comment by jordanmccullough** [comment]
All in favor of keeping with the look in the screenshot below, say aye. The current PR contains only commits that make this look happen.
screen shot 2013-05-22 at 11 16 42 am

**Comment by matthewmccullough** [comment]
Aye.

**Comment by brntbeer** [comment]
:+1: :ship:

**Comment by jordanmccullough** [comment]
Alright, I'm going to take @tlberglund's earlier comment as a :+1: for now to complete the team's consensus on this. :ship:ing!

**Comment by brntbeer** [comment]
woot! glad this went through

**Pull request merged**
