### PR TITLE
Impress improvements

### PR DESCRIPTION
**Pull request by benbalter**
A few impress improvements from trying to update the Pages deck...
- sniff slide ID from slide/section title for better permalinks
- remove generic title/description
- move header include to layout for simplicity
- w h i t e  s p a c e
- remove commented out code
- properly respect cover flag
- properly respect header flag
- strip demo css, add in bare bones structural css as standalone file

cc @jordanmccullough

### CODE REVIEW

**Comment by jordanmccullough** [comment]
@benbalter Thanks for the ImpressJS integration improvements.

Looks like the new stylesheet update generally built for RevealJS is blowing a few chunks with ImpressJS. Let me see what tweaks I can do to resolve this. From there, this PR looks solid and ready to :ship:.

**Comment by jordanmccullough** [comment]
This is what I intend on fixing, if anyone needed a visual reference of the style hiccups in the ImpressJS theme.

screen shot 2013-05-05 at 8 53 44 pm

**Comment by jordanmccullough** [comment]
Stylesheet shared between RevealJS and ImpressJS still needs attention, but HydeSlides plugin now provides rudimentary ImpressJS parsing and slide controls.

**Comment by matthewmccullough** [comment]
I confess I have played very little with Impress.js besides what you showed me over a dinner table or such. What's the first thing I should try here after it ships? Ship it if @brntbeer and @benbalter say so (Tim and I are in the air over the ocean)

**Comment by jordanmccullough** [comment]
First thing to try is flipping a slide deck from `layout: hydeslides-revealjs` to `layout: hydeslides-impressjs`. TOC will work ("simple mode" right now), the transitions (rotates, scales) are fun, etc.

A few more iterations are needed over the actual template (which enforces the various animation behaviors) but it's functional and a good start.

**Comment by matthewmccullough** [comment]
@jordanmccullough I don't want to create any extra work, but for test-driving, could we have a duplicate of Foundations with just the layout switched?  I mean, we don't have to maintain both long term, but it would be a fun an easy way to test drive both side by side.

**Comment by jordanmccullough** [comment]
@matthewmccullough Good point. "Temporary" Foundations deck in `presentations/git-foundations-impress.html`.

**Comment by jordanmccullough** [comment]
Finishing today. Resolving styling problems/collisions with RevealJS vs. ImpressJS slide selectors. Also performing a reverse merge and resolving merge conflicts so this PR will be easily approved once final changes area ready.

**Comment by jordanmccullough** [comment]
Stylesheets now work cleanly across RevealJs/ImpressJS frameworks.

screen shot 2013-05-24 at 5 12 05 pm

**Comment by jordanmccullough** [comment]
Fixed sticky note styling across ImpressJS and RevealJS.

Screenshots of ImpressJS slide styling and components (near 100% similarity to original RevealJS):
screen shot 2013-05-24 at 7 31 00 pm
screen shot 2013-05-24 at 7 27 08 pm
screen shot 2013-05-24 at 7 27 01 pm

**Comment by matthewmccullough** [comment]
Looks great from the screenshots.  Let me know if you want me to pull this branch and review it on my local machine and open `presentations/git-foundations-impress.html` and drive it end to end.

**Comment by jordanmccullough** [comment]
@matthewmccullough One more thing I need to address, and that is the build-out steps currently only supported in RevealJS. So the incremental graphics of some diagrams are currently still ~~broken~~ not fully functional with ImpressJS just yet. Final commits soon!

**Comment by jordanmccullough** [comment]
Ready to :ship:! Build out fixes for static diagrams (for time being) in ImpressJS completed.

screen shot 2013-05-27 at 4 32 00 pm

**Comment by jordanmccullough** [comment]
@matthewmccullough This PR also includes a commit that updates the ref for the HydeSlides-Plugins submodule.

**Comment by matthewmccullough** [comment]
:shipit:

**Pull request merged**
