### PR TITLE
Create new Gemfile.lock to reflect latest Gem releases

### PR DESCRIPTION
**Pull request by jordanmccullough**
Gem update of interest includes Jekyll 1.1.0, leaping
from the 0.12 release previously reflected in the
Gemfile.lock.

### CODE REVIEW

**Comment by jordanmccullough** [comment]
Anyone have thoughts why the update to the Jekyll gem to 1.1.0, and running with the new "subcommands" for `serve -w` turns up like this:

screen shot 2013-07-15 at 10 21 05 am

Not seeing this occur in any other projects that run on 1.1.0 or 1.0.3.

**Comment by brntbeer** [comment]
@jordanmccullough yeah, i've seen this before. 

totally forget how to fix, but i can jump on this and play around with it to ensure we have an updated jekyll locally

**Comment by brntbeer** [comment]
@jordanmccullough wanna take a look at it now? Seems tobe failing on `presentations/_posts/education/git/0001-01-01-The-Brief-Tour.md` and `presentations/_posts/foundations/git/0001-01-01-The-Brief-Tour.md`

**Comment by jordanmccullough** [comment]
@brntbeer Thank you! Looks like we're up and running on Jekyll 1.1.0.

Commit 70e66ae is a workaround as there seems to be a build issue with this release of Jekyll and Liquid elements. The markdown of the two files contained only a YAML frontmatter and `{capture <var> }` piece of content. The only workaround at present was to include placeholder plaintext prior to the `capture`.

Feel free to merge, or let me know if there is anything further before we :ship: it.

**Comment by brntbeer** [comment]
No problem! Thanks for figuring out that issue!

**Comment by brntbeer** [comment]
and the update to jekyll :heart_eyes:

**Pull request merged**
