### PR TITLE
Fixed HydeSlides location of _layouts & _includes

### PR DESCRIPTION
**Pull request by jordanmccullough**
Resolved issued of Jekyll firing from root of teach.github.com and not reaching HydeSlide Jekyll dependencies (_layouts, _includes).

Moved HydeSlides depedencies to root _layouts and _includes

### CODE REVIEW

**Comment by matthewmccullough** [comment]
Tried http://teach.github.com/presentations/git-foundations.html#/ and get a page, but still no styling that makes it a "reveal" preso.  Any thoughts on what I can change on the plane to make it work? :grin:

**Comment by brntbeer** [comment]
I'll also give a :+1: if we put something in the readme for how to add presentations :grinning:. Would make it easier for people adding their slides.

**Comment by jordanmccullough** [comment]
Resolved as of 30s ago.

**Comment by jordanmccullough** [comment]
README update coming momentarily.

**Comment by brntbeer** [comment]
woo! thanks mang!

**Comment by matthewmccullough** [comment]
Beautiful.  Looks like 5f560ff7a18e2c80ec0ea0180a60c8bb884abc8a fixed it all up! Gorgeous!

**Pull request merged**
