### PR TITLE
Update HydeSlide Plugin rev, resolves highlighting and performance

### PR DESCRIPTION
**Pull request by jordanmccullough**
Resolved the TOC active slide highlighting issue, cleans up JS with more efficient callback messaging functions.

### CODE REVIEW

**Comment by matthewmccullough** [comment]
Is this ready to go?  Is it merely the HydeSlides submodule update?  I'll try it locally and I'll remember to blast the cache this time to make sure it works. :)

**Comment by jordanmccullough** [comment]
Yes, I've tested it, but please verify. That would be great.

Once you confirm, please :ship:.

**Comment by jordanmccullough** [comment]
Sample of the highlighting improvement:
screen shot 2013-05-29 at 2 50 09 pm

**Comment by brntbeer** [comment]
oh man that looks great

**Comment by matthewmccullough** [comment]
I pulled and tested locally with a `submodule update` and it looks fine. Do it.

**Pull request merged**
