### PR TITLE
Remove "categories" unused YAML

### PR DESCRIPTION
**Pull request by jordanmccullough**
This tidies up all slides and discards the "categories" YAML field that was never used. Simplifies and avoids any confusion why this field is on the markdown files.

### CODE REVIEW

**Comment by tlberglund** [comment]
Checked this out locally, and it seemed sane to me. I would :shipit: if I were you. :)

**Comment by matthewmccullough** [comment]
This was an attempt to hide the slides from the auto-generated [category list page](http://teach.github.com/categories/). It didn't work out very well due to Jekyll being Jekyll and thus our new solution is to just have a [one-page-site](https://github.com/github/trainingteam/issues/475) that is statically crafted. Win. :+1:

**Comment by tlberglund** [comment]
@matthewmccullough :cool:

**Comment by matthewmccullough** [comment]
I might have miscommunicated.  Meaning, the reason this cruft was in here was me.  Jordan is playing janitor to my litter.

**Pull request merged**
