### PR TITLE
Fix Content Overflow for All Slides in Foundations

### PR DESCRIPTION
**Pull request by jordanmccullough**
This addresses Issue #231 (thanks @brntbeer!) by forcing line breaks within the Markdown. This solution works around any CSS hackery which collides with dynamic RevealJS scaling.

### CODE REVIEW

**Comment by jordanmccullough** [comment]
/ cc @github/training-team for a quick check and :+1:

**Comment by brntbeer** [comment]
http://localhost:4000/presentations/git-foundations.html#/20/3 

currently runs off screen on bottom and right side!

**Comment by brntbeer** [comment]
otherwise, this is amazing

**Comment by jordanmccullough** [comment]
Resolved slide 20/3 by separating the Difftool and Mergetool content.

screen shot 2013-11-28 at 8 27 03 am
screen shot 2013-11-28 at 8 27 06 am

**Comment by jordanmccullough** [comment]
Closing without merge in favor of [this PR](https://github.com/github/training.github.com/pull/139) following the content migration to https://training.github.com.

**Pull request closed without merging**
