### PR TITLE
HS TOC Plugin - Now Includes Notes

### PR DESCRIPTION
**Pull request by jordanmccullough**
The HydeSlides TOC Plugin (aka Launcher) now supports parsing the slide deck structure for notes.

Any active slide with notes will show the notes content next to active TOC marker in bubble. (Screenshots). _Notes content is authored in Markdown, formatted HTML appears in the TOC Notes bubble._

Screen Shot 2013-03-27 at 8 26 56 PM
Screen Shot 2013-03-27 at 8 25 59 PM

### CODE REVIEW

**Comment by jordanmccullough** [comment]
Hold on the PR approval. Caught an error in the Notes markdown for the majority of Foundations slide content.

**Comment by jordanmccullough** [comment]
Per-slide (Post) files updated with new include for revised Liquid template to include notes wrapper. See screenshot for Markdown now appearing correctly in the TOC Notes bubble.

Screen Shot 2013-03-27 at 8 44 59 PM

**Comment by tlberglund** [comment]
@jordanmccullough The `C` key should cause the TOC view to launch, right? I have merged this locally with `master`, and I can't get the TOC to pop up.

**Comment by jordanmccullough** [comment]
@tlberglund Locally or on [teach.github.com](http://teach.github.com/presentations/git-foundations.html#/)? Have you run `git submodule init` and `git submodule update`?

The plugins for HydeSlides/RevealJS that I've developed are in a submodule.

**Comment by tlberglund** [comment]
Ah, forgot to update the submodules. Thanks. :)

_This has never happened before_. To anyone.

**Pull request merged**
