### PR TITLE
Format transcript to improve readability by separating users and messages

### PR DESCRIPTION
**Pull request by randomecho**
Proof of visual concept to see how things would look if we only had lines of the transcript that went no farther than 125 and aligned the names and messages in a way to more easily track who typed what.

On second viewing, 120 might be better on the rendering view on the repo, but at the GH pushed, it may still work at 125.

(The smart thing to do would have been to actually write a little script to handle this experiment instead of listening to some podcast and manually spacing things out.)

Feedback, pointers or heads up appreciated. Just tried out one section to see if/how things would go.

### CODE REVIEW

**Comment by brntbeer** [comment]
I :heart: x:100:  this. Any reason why you chose 125 ?

Also yes, a script to do this would be awesome too!

**Comment by matthewmccullough** [comment]
@randomecho It is so agonizing that I can't find any "clean" text based way to export from the Campfire transcripts.  Only HTML and PDF and Copy-And-Paste in both cases (Okay, I could Watir the HTML copy and paste probably).  Any script to help stylize, strip and polish like you did here would be :musical_score: to my ears.

**Comment by matthewmccullough** [comment]
@brntbeer I'll leave it to you on the merge decision here regarding the 125-width.  My two cents is that we can always play with the width, but it certainly looks quite a bit better even with this!  Thanks @randomecho !

**Comment by randomecho** [comment]
125 "looked" like the best line drop to display when viewing the classnotes as they currently sit on teach.github.com

Was also thinking of 80 wide on the message, which if you account for a long username shouldn't be more than 100-110 wide on average. 

That is if you see 

```
matthewmccullough   message here 
```

(username, three spaces, start of message) as being the longest username in the chatscripts. Anything shorter than a message width of 80, say 50, seems like your eyes would be darting back and forth too much.

**Comment by randomecho** [comment]
Wrote up a Ruby script to further this concept https://github.com/randomecho/ironing-board

Should be able to take in the raw transcript dump and neaten it out like the example in this PR.

**Comment by matthewmccullough** [comment]
Amazing.  Will use this for my next class next week!

**Comment by matthewmccullough** [comment]
Used @randomecho's Ironing Board today.  Will open a PR on it.  Thanks a ton @randomecho !

**Pull request merged**
