### PR TITLE
Fix commit tree diagram typos/errors

### PR DESCRIPTION
**Pull request by jordanmccullough**
Tree node in diagram referenced to blob elements when label should be tree ref.

screen shot 2013-07-16 at 9 22 02 am

//cc @tlberglund

### CODE REVIEW

**Comment by jordanmccullough** [comment]
@github/training-team: Would like to get this fix live as soon as possible. I can't believe this diagram typo has been around so long without any of us seeing it until now. Thanks @tlberglund

**Comment by izuzak** [comment]
Also, the commit node visually points to the tree node labeled as "7e8b1", but the text within the commit node itself says: "tree: a10b3". :question:

**Comment by jordanmccullough** [comment]
@izuzak Thank you so much for that observation. I've now corrected the commit's tree ref as well.
screen shot 2013-07-18 at 8 25 22 am

**Comment by matthewmccullough** [comment]
Looks good to :shipit: to me!

**Comment by randomecho** [comment]
If you're in the mood for pedanticism, 

```
// Javascript
```

should be 

```
// JavaScript
```

**Comment by matthewmccullough** [comment]
@randomecho Precision here has an amplified effect of making us look really good elsewhere.  So thankful, as always, for your sharp eye.

**Comment by tlberglund** [comment]
@randomecho That should be _pedantry_, not pedanticism. Correction inception!



(And anyway, when it's you, we're always in the mood for corrections. Thank you! :grinning:)

**Pull request merged**
