### PR TITLE
New GitHub Branding Slide Deck Theme

### PR DESCRIPTION
**Pull request by jordanmccullough**
Cleans up the slide deck theme (Cobalt) and improves contrast for projector-intended showcasing.

Colors are from Primer and stay within branding colors. 

New ideas for bubble/sticky-note callout still a WIP.

@github/training-team discussion still necessary and further refinements at this initial PR before merging in.

screen shot 2013-04-30 at 3 39 58 pm
screen shot 2013-04-30 at 3 40 21 pm
screen shot 2013-04-30 at 3 40 36 pm

### CODE REVIEW

**Comment by jordanmccullough** [comment]
screen shot 2013-04-30 at 5 31 54 pm

**Comment by matthewmccullough** [comment]
I really love the GitHub Apex font and the new clear-it-is-a-console command window.

**Comment by brntbeer** [comment]
@jordanmccullough  it seems on `diff` and `branch` slides have line spacing really close to each other, is that because of screen size or what? looks totally fine in `log formatting`

**Comment by brntbeer** [comment]
er, to clarify, i mean your images from above

**Comment by jordanmccullough** [comment]
@brntbeer Do you mean the header-to-content spacing? I've tweaked that, so the `Log` slide example should definitely look better. Let me know if I'm not seeing it otherwise... Thanks!

**Comment by jordanmccullough** [comment]
Revised the styles and fine-tuned the line heights and such a bit more.

Spacing between headers (when not forced-hidden with YAML) now include a bit more breathing room between title and content.

Sticky notes look far better in their original, skeuomorphic form (instead of callout bubble in the prior screens).

Bullet points, which when used sparingly, are still content components of the slide deck. However, I feel the slides with bullets only are missing any sizzle. Team's thoughts on this are, of course, welcomed.

screen shot 2013-04-30 at 7 32 05 pm

screen shot 2013-04-30 at 7 30 57 pm

**Comment by brntbeer** [comment]
Didn't mean anything about header and content, the text inside the code
blocks (the example commands to run, in green text on black background) is
practically touching on diff and branch picture shown above where as the
lines between example text for "log" picture are nicely spaced

On Tuesday, April 30, 2013, Jordan McCullough wrote:

> @brntbeer https://github.com/brntbeer Do you mean the header-to-content
> spacing? I've tweaked that, so the Log slide example should definitely
> look better. Let me know if I'm not seeing it otherwise... Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/github/teach.github.com/pull/142#issuecomment-17263690
> .

## 

Brent Beer
GitHub:Training
http://training.github.com
https://github.com/brntbeer

**Comment by jordanmccullough** [comment]
Aha! So glad you clarified. Thanks.

Yes, I did fix the line-height on the `pre code` blocks, so the spacing between lines of code now should look much better.

The first draft was certainly to close together. Since the most recent commit, all code blocks will look like the screenshot [here](https://github.com/github/teach.github.com/pull/142#issuecomment-17261113).

**Comment by jordanmccullough** [comment]
Just a brief heads up, but given the big theme overhaul, this PR will also include some diagram and build-out effect improvements.

**Comment by jordanmccullough** [comment]
Per [this comment](https://github.com/github/teach.github.com/pull/142#issuecomment-17265628) the diagrams are also receiving a major overhaul and improvement in this PR.

Thanks to @brntbeer for pointing out the missing "`" on the rebase diagrams.

screen shot 2013-05-01 at 10 42 29 am
screen shot 2013-05-01 at 10 42 39 am

**Comment by jordanmccullough** [comment]
Network diagram showing local branches, remote branches, and upstream now displays in five build-out steps. Demonstrates the difference between `fetch` and `pull` more clearly.

screen shot 2013-05-01 at 11 53 50 am

**Comment by brntbeer** [comment]
@jordanmccullough wondering about the network slide. i hate to nit-pick but could we put the arrow-image for `pull` to be on a different line (like, below the fetch arrow)? at first glance it almost looked as though all pull does is go from remote to local.

**Comment by jordanmccullough** [comment]
@brntbeer A good insight on the Network build out. I had perceived that the talking point, when we're presenting from the deck, was to explain the `pull` as a fetch-merge process.

Now seeing how there could be some disconnect if anyone else reviewing or learning from the slides though. This certainly needs to be a separate arrow.

**Comment by brntbeer** [comment]
I could go either way on that arrow! makes sense when moving through it on your own actually, but as a standalone image i was confused. Either way!

**Comment by jordanmccullough** [comment]
@brntbeer The Network diagram has been updated to include the "pull" arrow on a separate line from the "fetch". Looks much clearer now.

**Comment by brntbeer** [comment]
Love the network change!

**Comment by jordanmccullough** [comment]
Default fonts now fall back to Helvetica Neue, then Helvetica, when Apex isn't available.

This is what the fonts look like on a system ~~with~~ without Apex installed:
screen shot 2013-05-01 at 3 58 11 pm

screen shot 2013-05-01 at 3 58 38 pm

screen shot 2013-05-01 at 3 56 45 pm

**Comment by brntbeer** [comment]
I think once the font for this image is fixed, i'd call this good. Is it always going to look like this without Apex?

screen shot 2013-05-01 at 12 54 27 pm

**Comment by jordanmccullough** [comment]
@brntbeer We totally posted question/answer at the same time. Talk about timing!

See [this comment above](https://github.com/github/teach.github.com/pull/142#issuecomment-17309276).

**Comment by brntbeer** [comment]
yeah i know but the "mirror" or whatever it is of that font on my above image still looks broken.

**Comment by jordanmccullough** [comment]
Dang! I've got to purge that style from the ReavealJS core styling. Can't stand it, and it's breaking when I tweaked some overrides with our custom font. I'll tackle this then we can call the new theme done.

**Comment by brntbeer** [comment]
agreed!

On Wed, May 1, 2013 at 3:06 PM, Jordan McCullough
notifications@github.comwrote:

> Dang! I've got to purge that style from the ReavealJS core styling. Can't
> stand it, and it's breaking when I tweaked some overrides with our custom
> font. I'll tackle this then we can call the new theme done.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/github/teach.github.com/pull/142#issuecomment-17309604
> .

## 

Brent Beer
GitHub:Training
http://training.github.com
https://github.com/brntbeer

**Comment by jordanmccullough** [comment]
Screen shot of RevealJS hyperlink overrides for inactive and active state. Link on hover now highlights with "brand-darkGrey" bubble background and inverted foreground (text) color.

screen shot 2013-05-01 at 7 15 43 pm

**Comment by jordanmccullough** [comment]
Alright @github/training-team, [this](https://github.com/github/teach.github.com/pull/142) PR is ready to :ship:!

**Comment by matthewmccullough** [comment]
Looks great!

**Comment by brntbeer** [comment]
Awesome! Good work Jordan!

On Thursday, May 2, 2013, Matthew McCullough wrote:

> Looks great!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/github/teach.github.com/pull/142#issuecomment-17325966
> .

## 

Brent Beer
GitHub:Training
http://training.github.com
https://github.com/brntbeer

**Comment by jordanmccullough** [comment]
Thanks guys! The new multi-step build-out of diagrams made today's class amazing. Noticed a few more diagrams that need some step-builds, but that'll be another PR when I catch my breath from this week.

**Comment by matthewmccullough** [comment]
Used this for class today at Beats Audio. Went very well. White is definitely the best color for deficient projectors,

**Comment by jordanmccullough** [comment]
Awesome! Glad to hear it. There are a few more rounds of improvements, but one of the big leaps in this upgrade is the better diagrams. Really helped with my class today as well.

**Comment by benbalter** [comment]
Wow. This looks amazing. Will work to convert the pages deck over.

Quick question. I don't haz dat Apex hotness. Do I need to install it locally? If so, how so?

**Comment by benbalter** [comment]
I haz Apex. :smile: 

Thanks. Again, @jordanmccullough, awesome, awesome, awesome stuff.

**Pull request merged**
