### PR TITLE
Slide notes migration fix

### PR DESCRIPTION
**Pull request by jordanmccullough**
Resolves the missing _includes template following the semi-successful migration and update to the latest HydeSlides rev.

All _includes paths in _all_ `_posts` have now been updated.

### CODE REVIEW

**Comment by jordanmccullough** [comment]
@github/training-team Please review at earliest possible, as otherwise the slide breakage is out in the wild, right now. :frowning:

**Comment by tlberglund** [comment]
Thanks for the quick turnaround, @jordanmccullough!

**Comment by jordanmccullough** [comment]
Thanks for catching that. We're back up and live with "happy" slides.

Screen Shot 2013-04-17 at 4 06 54 PM

**Comment by tlberglund** [comment]
:boom:

**Pull request merged**
