### PR TITLE
Add AI file with slide deck vector diagrams

### PR DESCRIPTION
**Pull request by jordanmccullough**
Provides access to raw graphical files for contributes to edit and
adjust as needed for generating PNGs used in slides.

screen shot 2013-08-08 at 3 12 59 pm

### CODE REVIEW

**Comment by tlberglund** [comment]
@jordanmccullough I am guessing your intent is to make this file available over the web, should anyone discover it. I can't think of a reason _not_ to do that, but I just wanted to surface the question to ~~be a pain~~ make sure you didn't mean to set a `.gitignore` or anything.

**Comment by jordanmccullough** [comment]
No `.gitignore` intended. I want to set this file free from the confines of my local machine. :scream:

Anyone is welcome to peer into the file contents, but this, I find, is a far better place for the AI file to live--right along side the `/presentations` where it's resultant artifacts also live.

If that's a :+1: from you, let's :ship: it.

**Comment by tlberglund** [comment]
:shipit: good.

**Comment by tlberglund** [comment]
Also, when I said `.gitignore`, I was actually thinking whatever the equivalent of `.htaccess` is here, which I think is not even a thing. So the original comment makes no sense upon reflection. :)

**Pull request merged**
