### PR TITLE
Jekyll, GitHubPages, and You! deck, per #70

### PR DESCRIPTION
**Pull request by benbalter**
Screen Shot 2013-03-29 at 1 55 02 PM

**Todo**:
- [ ] Pretty pictures, octocats, etc.
- [ ] Tightening the language a bit to make things clearer to n00bs
- [ ] Screencast

cc @matthewmccullough, @brntbeer

### CODE REVIEW

**Comment by benbalter** [comment]
err, looks like the @mention didn't work, so cc #70

**Comment by brntbeer** [comment]
So full of win.

**Comment by brntbeer** [comment]
Will be  checking this out locally and giving it a look over shortly. thank you so much

**Comment by benbalter** [comment]
Also, if it's easier, through the magic of the internet, http://ben.balter.com/teach.github.com/presentations/github-pages-jekyll-you.html

**Comment by brntbeer** [comment]
URL win!.

http://ben.balter.com/teach.github.com/presentations/github-pages-jekyll-you.html#/5/4 doesnt render properly on a smaller laptop screen by the way =(

**Comment by brntbeer** [comment]
it attempts to adjust to a point, but there's a lot on that page.

**Comment by benbalter** [comment]
Perhaps we could <del>steal</del> borrow a feature from https://github.com/bartaz/impress.js/ where the slides auto-scale to fill the screen? That way it'd work on mobile as well, e.g., http://ben.balter.com/hacking-apis-from-the-inside-out-disruptively/#/title

@jordanmccullough any thoughts?

If not, simple enough to break into separate slides

**Comment by jordanmccullough** [comment]
@benbalter crazy timing! Was building out a Jekyll layout for HydeSlides to support ImpressJS. 

However, to address the more immediate problem, I do need to look into the scaling issue/fix for HydeSlides using RevealJS. There should be some built-in scaling but will need to investigate why that's not achieving the desired results.

**Comment by benbalter** [comment]
Glad to be a guinea pig. Also, if it's helpful, I put this together a while back and have been using it when I needed decks: https://github.com/benbalter/hacking-apis-from-the-inside-out-disruptively

**Comment by matthewmccullough** [comment]
@benbalter I'm about a third of the way through reviewing this in detail. Nice stuff!  How would you prefer me to suggest changes to the PR here?  Just call them out?  Happy to also try and just make them, but would need access to your fork.  Also happy to ship it (my inputs are mostly little tweaks, order, segmentation) and then open a PR as tuning on this.  Let me know...

**Comment by benbalter** [comment]
Your call. Welcome to just call them out, otherwise, added you as a collaborator on my fork.

Learning, that next time, the smarter thing to do would be to push to a branch on the main repo and submit a pull request from one branch to another?

**Comment by benbalter** [comment]
Or, if we really want to mux things up further, I guess you could always submit a pull request to my fork. :smile:

**Comment by matthewmccullough** [comment]
@benbalter Cloned your fork. Committing locally on plane. Pushing upon landing.

**Comment by matthewmccullough** [comment]
@benbalter Let me know if the nature of the tweaks I did here are OK. If so, I'll finish up the same through the remainder of the deck.

I can't tell you how awesome it is to have this important deck ready. Our students in class yesterday in San Francisco were saying "so, tell me about this Pages thing on GitHub..."  Clearly a sign we need this nao.

**Comment by benbalter** [comment]
:+1:

Really coming together, and much easier for a wider audience to grasp the way you're breaking things out.

Exactly. Jekyll is simple enough to be dangerous. Besides, I'm just selfish. Tired of explaining the same thing 10x a week on this coast!

**Comment by matthewmccullough** [comment]
Nearly done with some granulizing. Check out the latest on your branch. I
think I only have 10ish slides to review. Baby time impacted last week's
efforts. I would love to put this back in your hands to ship as you see
fit, later today.

On Thu, Apr 4, 2013 at 11:18 AM, Ben Balter notifications@github.comwrote:

> [image: :+1:]
> 
> Really coming together, and much easier for a wider audience to grasp the
> way you're breaking things out.
> 
> Exactly. Jekyll is simple enough to be dangerous. Besides, I'm just
> selfish. Tired of explaining the same thing 10x a week on this coast!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/github/teach.github.com/pull/111#issuecomment-15910951
> .

## 

Sincerely,
Matthew McCullough
GitHub:Training
http://github.com/training
Author of O'Reilly's Git Master Class
http://bit.ly/ogitvid
http://bit.ly/ogitvid2

**Comment by benbalter** [comment]
Sounds good. Totally understandable. :) Are we still shooting for a video / screencast, or just ship as slides?

Also, if you haven't already, should run `rake site:preview` on [Jekyll 1.0beta](https://github.com/mojombo/jekyll). Been working on the docs there as well. Good stuff.

**Comment by jordanmccullough** [comment]
@benbalter Per your mention of ImpressJS, just implemented this with HydeSlides. PR and update to the Training Team's repo en route for delivery today.

**Comment by matthewmccullough** [comment]
@benbalter Once you give my edits the :+1:, then the screencast happens. We should discuss how/who. I surely never want to take something away that you would want to record, but would be happy to record this in the very near term.

**Comment by benbalter** [comment]
Deprecating this pull request in favor of #122 which is a branch of the repo, rather than a private fork.

**Comment by benbalter** [comment]
@matthewmccullough :+1: on all your edits. Looks awesome. If you've got time, would be awesome if you could do the screencast since you've got the setup. 

Made a punchlist of outstanding issues on the new hotness that is #122. If you have uncommitted changes, feel free to commit them, and then we should be good to go. 

Can work with @jordanmccullough on the formatting, but that shouldn't have to be a blocker on the screencast.

**Comment by matthewmccullough** [comment]
Per #122, I'm all in for one tiny set of tweaks on a new PR after this ships and closes. Go forth, @benbalter on the merge when you are ready.

**Pull request merged**
