### PR TITLE
GitHub Features and Non-Technical Slide Deck

### PR DESCRIPTION
**Pull request by jordanmccullough**
A simplified slide deck for showcasing and touring GitHub.com features, terminology, and processes.

### CODE REVIEW

**Comment by matthewmccullough** [comment]
I am so excited to see this manifested as a HydeSlide deck!  I felt so bad having it as Keynote deck when I gave it.

**Comment by jordanmccullough** [comment]
@brntbeer You mentioned you were working on an outline in parallel to a slide deck, IIRC. Want to see how well this lines up and if it's a good start?

**Comment by brntbeer** [comment]
definitely never mentioned working on a slide deck, lol

**Comment by jordanmccullough** [comment]
Oops! Well, here it is! :wink: 

This was just quickly drafted up before the Nov. 20 GHfNP one hour presentation to new hires.

**Comment by brntbeer** [comment]
Also, it's a good first tour.  One thing i dislike though, is how large the images are. 500px width should be good enough here

**Comment by jordanmccullough** [comment]
Whoa, that's not right! Good catch @brntbeer. I'm checking if I failed to check in the stylesheet tweak (likely!) that results in the icons looking like this (they shouldn't).
screen shot 2013-11-27 at 6 46 27 pm

**Comment by jordanmccullough** [comment]
Fixed. Stylesheet didn't get committed with the original push for this PR. Here's the expected result now with the CSS fix:

screen shot 2013-11-27 at 7 00 01 pm

**Comment by brntbeer** [comment]
hahahaha yeah ok. that looks much better

**Pull request merged**
