### PR TITLE
Fresh, contrasty slide deck theme

### PR DESCRIPTION
**Pull request by jordanmccullough**
Inverted colors (white text, dark background), and used @jasonlong's [Arctocat](http://dribbble.com/shots/893577-Arctocat?list=users) as basis of color scheme.

Also included new support, which still needs refinement, for changing themes per slide deck.

Screenshots of new look:

Screen Shot 2013-03-12 at 7 42 06 PM
Screen Shot 2013-03-12 at 7 41 57 PM
Screen Shot 2013-03-12 at 7 43 58 PM

### CODE REVIEW

**Comment by jordanmccullough** [comment]
New static PNGs inverted.
Screen Shot 2013-03-12 at 7 50 43 PM

**Comment by matthewmccullough** [comment]
I like it a lot. Though an option for light/dark would be awesome too. Low grade projectors tend to work better as the bulb goes dim with black on white. Sad to have to think about this, but so many times the projector is ill-maintained.

**Comment by jordanmccullough** [comment]
Ah, the beauty of me having setup the theming as a per-slide-deck Markdown file. The original hasn't yet been migrated to the `themes` folder and pattern, but certainly can do before this PR gets merged.

**Comment by jordanmccullough** [comment]
See [this file in the PR](https://github.com/github/teach.github.com/blob/7e155fd18fd22d324c8a35e1e2e0ebfddb0a0d20/_layouts/hydeslides.html)  for how the theme is applied via the front matter:

**Comment by jordanmccullough** [comment]
@matthewmccullough Thanks for bringing this up. Just realized a little tweaking is still in order. Adding the original theme as configurable and fixing an oversight on where the theme front matter is setup.

**Comment by matthewmccullough** [comment]
:smile:

**Comment by jordanmccullough** [comment]
Done! Fallback strategy now in place. Default theme if no `theme` defined in front matter is the original. If you want to explicitly apply a theme, add the `theme: <themename>` in the slide deck front matter.

This PR is now ready to :ship:

**Comment by jordanmccullough** [comment]
Screenshots, just for the sake of it, of the original slide deck look. Will always apply as default, but also optionally specified as described above. Screen Shot 2013-03-12 at 10 28 04 PM
Screen Shot 2013-03-12 at 10 28 18 PM

**Pull request merged**
