### PR TITLE
Git Foundations Slide Deck using HydeSlides scaffolding

### PR DESCRIPTION
**Pull request by jordanmccullough**
Git Foundations first 20+ slides implemented using new scaffolding of Jekyll and RevealJS.

README.md contains info on state and use of HydeSlides of current iteration.

@github/training-team please review at your earliest. If approved, I intend on proceeding with Git Foundations full slide deck conversion, followed by Advanced Git.

### CODE REVIEW

**Comment by matthewmccullough** [comment]
Should it be accessible from http://teach.github.com/presentations/git-foundations.html ?

**Comment by jordanmccullough** [comment]
Um...Yes, it should. Checking now. :frowning:

**Comment by jordanmccullough** [comment]
@github/training-team Not seeing why the `git-foundations.html` isn't being gen-ed on the GH-Pages. I'd welcome a second set of eyes on this issue.

**Comment by matthewmccullough** [comment]
Looks like the page built. Tell me what you think @tlberglund and @brntbeer:

skitched-20130121-095235

**Comment by jordanmccullough** [comment]
Pulled and try to run Jekyll locally. The merge of the HydeSlides in GH-Pages isn't working on my box either. Comparing to my branch and the pull request to make sure something didn't get broken in the process.

Think it might have to do with Jekyll being run from root, rather than from my presentations dir.

**Pull request merged**
