### PR TITLE
Diagram Overhaul and Stylesheet Fixes

### PR DESCRIPTION
**Pull request by jordanmccullough**
Overhaul of all Foundations slide deck diagrams. Updating the look and feel as well as the way the visuals demonstrate Git concepts.

Stylesheet fix for fragment build-outs also included.

### CODE REVIEW

**Comment by jordanmccullough** [comment]
First draft of new look and feel and cleaner indication of HEAD during a branch demonstration.

foundations-fast-forward

**Comment by matthewmccullough** [comment]
@jordanmccullough This is crazy. You are telepathic. Yesterday, I was thinking, maybe we should iOS7 this and also bring it even more into the light modern realm. :sparkles:  I am going to go ham on the advanced deck's text content soon too.

**Comment by jordanmccullough** [comment]
@matthewmccullough So eerie, but also very awesome coincidence.

Also, in the interest of supporting internationalization, no words will be embedded in the imagery, other than Git-centric components, such as refs and file paths.

**Comment by jordanmccullough** [comment]
Example of recursive merge. Build steps would includes each commit and HEAD highlight. Demonstrates that commits can be against different branches by toggling back and forth.

foundations-recursive-merge

**Comment by tlberglund** [comment]
@jordanmccullough Those look great! While you're at it, what would you say to adding branch names to the merge example?

**Comment by jordanmccullough** [comment]
@tlberglund I explored using labels ("master", "feature") on the content rows representing branches, but it introduced a bit of bulk. In my mind, and from previous iterations of this diagram, usually an instructor's commentary is sufficient. In the case of self-guided learning using these slides, there are also the supplemental presenter notes. Does that seem reasonable approach?

Updated Recursive Merge Strategy diagram with files (added or removed) indicated with dot marker.

foundations-recursive-merge

**Comment by tlberglund** [comment]
@jordanmccullough It's perfectly reasonable. There isn't an obvious right or wrong answer here. When I'm in person and can gesture to the screen, I think this works fine, but I do think it's unclear online or in settings when I'm not able to do that. It's easy for us to map branch names to commits, but for people who are just thinking about this for the first time, it's still confusing.

So I remain persuaded that labels are right, but I'm fine proceeding without them. Also, despite being an intense non-fan of the iOS 7 aesthetic, I like the way these diagrams look. :)

**Comment by jordanmccullough** [comment]
@tlberglund I would feel negligent if I didn't provide a diagram with the branch labels as you requested, so here it is. :smile: 

After a bit more work with the structure and placement, I might just be convinced these are effective. :+1: 

foundations-recursive-merge-branches

**Comment by tlberglund** [comment]
@jordanmccullough Allow me to suggest another iteration before we vote on this. How about simply the words "master" and "feature" (no "branch" or top/bottom border decorations) _on the right side of the commits_. That way, each branch label stays close to its head commit, and moves as the diagram builds to reveal more commits. That visually emphasizes branch names as commit labels, rather than permanent swim lane designations. Worth trying?

**Comment by jordanmccullough** [comment]
Static image of branch labels--no decorations, no "branch" verbiage, always on right side of HEAD commit representation.

foundations-recursive-merge-branches

**Comment by tlberglund** [comment]
@jordanmccullough I think that's perfect, assuming the branch names move appropriately from each frame to the next. You could even create two merge scenarios: one in which you merge `feature` into `master` (shipping the feature), and one in which you merge `master` into `feature` (keeping a feature branch up to date).

**Comment by jordanmccullough** [comment]
@tlberglund: Thanks. There are many variants coming for both training and self-guided learner's uses. A reverse merge is an excellent idea I hadn't thought of before. This _will_ happen! 

I was also considering a merge conflict in some manner, but first to the primary examples, then supplementary ones to follow. :boom:

**Comment by tlberglund** [comment]
@jordanmccullough I'd love pics for a merge conflict. To do that, though, you'd have to represent a non-conflicted merge in a visual way, probably by showing `theirs` and `ours` versions of a file, plus the `base` version, with blocks of text contributed from each. That woulds set up the user to see and understand a conflict.

**Comment by jordanmccullough** [comment]
Quick update. Diagrams now in-browser and working for Recursive Merge example.
screen shot 2013-09-20 at 1 46 34 pm

**Comment by jordanmccullough** [comment]
### Fast Forward Merge

ff-diagram-example

**Comment by jordanmccullough** [comment]
@tlberglund @brntbeer @matthewmccullough: Before I proceed with the conversion of _all_ remaining diagrams (rebase, merge conflicts, what is a commit, etc.), can you provide a quick :+1: or :-1: on the changes' look and feel?

[Animated gif of Fast Forward steps](https://github.com/github/teach.github.com/pull/204#issuecomment-24849347)

[Static view of Recursive Merge steps](https://github.com/github/teach.github.com/pull/204#issuecomment-24836747)

**Comment by brntbeer** [comment]
God these look so amazing.

I love how they step through and highlight at each step. but one thing I still don't like is the animation on FF merge. I know this will have some explanation from us that goes into it. but what about dropping the entire feature branch down to being lined up with master and forming a straight line?

When you drop it down to being straight with the master branch, it correctly illustrates what the graph looks like after the merge (it's almost as if no work was done on a branch at all). the arrow to show master / feature at the same point is a really nice touch as well.

**Comment by matthewmccullough** [comment]
@brntbeer's point about dropping the line down for fast forward would indeed help some of my students. I drew that out for the BBN folks on my AirSketch app to help them get why it was drawn in a straight line in GUIs like GitK.

Really, really like these.

**Comment by jordanmccullough** [comment]
@brntbeer Good point about the fast forward and clean line of history. Diagram updated and now looks like this: 

merge-ff-revised

**Comment by matthewmccullough** [comment]
@jordanmccullough :boom: :eyes: :+1:

**Comment by jglovier** [comment]
@jordanmccullough looking good - great improvement! :thumbsup: 

What about removing the stroke around the boxes in favor of just using a background color (serving to bring more visual hierarchy to the box's contents).

Something like this maybe?
image

It's mostly just a style thing, so if you like it run with it. Otherwise, carry on sir.

**Comment by jordanmccullough** [comment]
@jglovier Excellent change. Going through a few quick iterations to update the AI symbols to match.

Only things that might stick around in the final diagrams are the white stroke on the arrows. I think it "cuts through" a bit more on the overlap of the boxes.

:heart: the suggestion and visual example. Thanks.

**Comment by jordanmccullough** [comment]
My other concern is contrast ratios. The black outline on white provides the highest possible. As these slides are often shown on projectors, I'm thinking of potential lack-of-contrast issues under some viewing conditions.

Any suggestions how we'd best numerically evaluate that?

**Comment by matthewmccullough** [comment]
I don't have numbers, but from using my PPAP Sanity Test Deck (http://presentationpatterns.com/blog/pppst/), I can tell you that grey has a significant chance of not showing up in the various venues that we present. Good point to bring this up early.

Sincerely,
Matthew McCullough
GitHub:Training
http://training.github.com
Author of O'Reilly's Git Master Class
http://bit.ly/ogitvid
http://bit.ly/ogitvid2
Co-Author of O'Reilly's Version Control with Git Book
http://bit.ly/ogitbook

**Comment by jordanmccullough** [comment]
### Tone and Shape Tweaks

As the diagrams for merge and rebase were already completed when @jglovier brought up the style modification, this PR will finish up with the current look of outlined "boxes". Some investigation will also be necessary to ensure the [grey tones are visible](https://github.com/github/teach.github.com/pull/204#issuecomment-24944219) with low-contrast projectors. Therefore [this issue](https://github.com/github/teach.github.com/issues/207) has been opened to keep track of a future round of revisions.

### Preview of Rebase

_The titles of the slides will also be fixed to avoid the repeat wording_

rebase

**Comment by jglovier** [comment]
> Only things that might stick around in the final diagrams are the white stroke on the arrows. I think it "cuts through" a bit more on the overlap of the boxes. 

:thumbsup: to that. Mine honestly didn't include it because I simply couldn't find a way to add a white border to the line elements in Sketch.

> My other concern is contrast ratios. The black outline on white provides the highest possible. As these slides are often shown on projectors, I'm thinking of potential lack-of-contrast issues under some viewing conditions.
> Any suggestions how we'd best numerically evaluate that?

So no, I don't think there's really any quantifiable, "numeric" way to evaluate that. But that's okay. The point of getting rid of the box border is to let the content stand out more. So if the background-color doesn't show up very well in a projector setting, that's okay because the content (being black) still will and that's the important part. In fact, it's kind of the point of the tweak. :-)

That's my theory anyway. In practice it may prove differently.

**Comment by jordanmccullough** [comment]
@jglovier I hear you. I definitely want to pursue your proposed design tweaks, as it is cleaner without the borders. With [the issue documenting](https://github.com/github/teach.github.com/issues/207) this, I've put the gray-box version as a round-two of the new look. :cool:?

Again, appreciate all the constructive and design-focused feedback. I'll see to the tweaks happening :soon:.

**Comment by jglovier** [comment]
@jordanmccullough :thumbsup:

**Comment by jordanmccullough** [comment]
Rebase Interactive diagram demonstrates 1. Remove (eliminating the commit altogether) 2. Squash (collapsing two files commits to one) 3. Edit (removing a file from a commit).

rebase-i

**Comment by jordanmccullough** [comment]
### Remotes

Updated to use iconography to better communicate what occurs at each step, and which branch is affected (indicated by highlight).

remotes

**Comment by jordanmccullough** [comment]
three-stage

**Comment by matthewmccullough** [comment]
Amazing. So illustrative and far clearer with the icons.

**Comment by matthewmccullough** [comment]
> Rebase Interactive diagram demonstrates 1. Remove (eliminating the commit altogether) 2. Squash (collapsing two files commits to one) 3. Edit (removing a file from a commit).

Suggestion (discardable one) to use four character hashes since that's the legal minimum.  I know I started this shorter 3-char bad habit, but I regret it. :grin:

**Comment by jordanmccullough** [comment]
Given how far along, would it seem prudent to wrap up the diagrams with the three-char refs then revisit? It's a bit of reworking given how far along and how many PNGs have been generated at this point.

I'm all :ear:s if my oversight would cause confusion in the slide deck.

**Comment by matthewmccullough** [comment]
> would it seem prudent to wrap up the diagrams with the three-char refs then revisit

Most definitely.  It was a silly late snipe on my part just for future thinking.

**Comment by jordanmccullough** [comment]
### Four States of Tracking

four-states

**Comment by matthewmccullough** [comment]
Man. So excited for these. This type of visualization helps so much in
class. Right now, I'm drawing them with Skitch each time.

**Comment by jordanmccullough** [comment]
This is now review-and-ship ready. Let's :ship: this thing!

**Comment by jglovier** [comment]
+bajillion for the icons. :zap:

**Comment by jglovier** [comment]
> Given how far along, would it seem prudent to wrap up the diagrams with the three-char refs then revisit? It's a bit of reworking given how far along and how many PNGs have been generated at this point.

BTW at some point it would be :cool: to redo the diagrams as html/css instead of PNGs. I'd love to tackle that someday.

**Comment by jordanmccullough** [comment]
@jglovier: We're thinking very much the same thing. :soon: for sure. Edibility for the win.

**Comment by tlberglund** [comment]
The _Commit - What is a Commit_ page is unhappy. Served locally, it's here: http://localhost:4000/presentations/git-foundations.html#/6/4.

**Comment by tlberglund** [comment]
On _**Remove & Move** - The Stages of Tracking_ (http://localhost:4000/presentations/git-foundations.html#/9/1), I love the new look and Octicons like everywhere else, but I like the old look that showed all state transitions on the screen at once. I recognize that figure as a state transition diagram, which anyone who has programmed state machines explicitly will also recognize. We're talking about state transitions, so i think the previous form is really useful.

**Comment by jordanmccullough** [comment]
### Commit

Fixing this. Oversight--somehow--on the new diagram development

### Remove & Move

Iteration on columnar-style :soon:.

**Comment by jordanmccullough** [comment]
### Remove & Move

Revised look:

screen shot 2013-09-24 at 5 38 02 pm

**Comment by matthewmccullough** [comment]
A thought: because I like to teach in a "parts, then the whole" could we keep both ways?  One would allow us to talk about how it works, looking at it from a "map" view while the other demos it in a stepwise fashion and lets us talk about it piece by piece.

**Comment by jordanmccullough** [comment]
@matthewmccullough Good point. I've brought in both diagrams, with the [simpler one](https://github.com/github/teach.github.com/commit/0d817bb00a235cbcf442561ff80630cf9b0175e3) appearing after the more detailed one. With the Jekyll TOC navigator, this should provide simple enough jumping so we can show one, the other, or both as desired.

**Comment by jordanmccullough** [comment]
### What is a Commit

Non-fragment diagram for starters. If build-out is necessary, will address in future iterations.

screen shot 2013-09-24 at 9 22 32 pm

**Comment by jordanmccullough** [comment]
Let's :ship: this--that is, unless anyone sees any glaring issues that break the content.

**Comment by matthewmccullough** [comment]
Looks good to me. Maybe one more :+1: ?

**Comment by tlberglund** [comment]
I forgot to mention in my comment that the _What is a Commit_ diagram lacks file/directory names. Happy to ship without them, but only if we get another PR immediately on the heels of this one to address that.

**Comment by jordanmccullough** [comment]
@tlberglund: absolutely.

On Wednesday, September 25, 2013, Tim Berglund wrote:

> I forgot to mention in my comment that the _What is a Commit_ diagram
> lacks file/directory names. Happy to ship without them, but only if we get
> another PR immediately on the heels of this one to address that.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/github/teach.github.com/pull/204#issuecomment-25078641
> .

## 

Jordan McCullough
GitHub Training
http://training.github.com

**Comment by jordanmccullough** [comment]
@tlberglund: This final commit should help make this PR fully :ship:able now. Ready to merge?

screen shot 2013-09-26 at 10 06 35 am

**Pull request merged**
