### PR TITLE
HydeSlides UI Update, Content Additions

### PR DESCRIPTION
**Pull request by jordanmccullough**
@tlberglund These are important tweaks that'll need a quick review and merge. This should give you a give you a good jump start on other slide chapters.
- New Chapter content for "stash", updated diagrams.
- Revised presenter notes in slide files to support markdown and simpler wrapping tag set.
- Revised layout of RevealJS split-mode.

### CODE REVIEW

**Comment by brntbeer** [comment]
One thing that i love so much about these changes is that the slides hold so well to a presentation principle of not overloading the page and the slide just being an anchor point.

well done sir.

**Comment by jordanmccullough** [comment]
Updating README to reflect, but please note that the querystring hack previously required for the presentation split mode/whats-next functionality is now deprecated. Only the full path (i.e. teach.github.com/presentations/git-foundations.html) is necessary to access slides and use `s` mode.

**Comment by jordanmccullough** [comment]
@brntbeer Thanks for the feedback. Looking forward to seeing this fully in use very soon.

**Comment by jordanmccullough** [comment]
Also styled up the Split-Mode a bit more to make the "What's Next" slide a bit more clear.

Screen Shot 2013-01-24 at 4 33 42 PM

**Comment by jordanmccullough** [comment]
Commit 0192ea5 tidied the _layouts and _includes so there isn't the previous clutter pollution of these shared Jekyll dirs. HydeSlides now uses only one _layout page, and all includes are sub-dir under the _includes.

**Pull request merged**
