### PR TITLE
Added first-draft Git Advanced slides

### PR DESCRIPTION
**Pull request by jordanmccullough**
These slides are a WIP for Advanced Class slide decks. From my audit, none of the content duplicates what can be found in Foundation's chapters and only builds upon them with more in-depth content.

### CODE REVIEW

**Comment by jordanmccullough** [comment]
Pondering name-spacing the chapter content to be more clear as to it's designation. The reason driving this is that we might need two "chapters" on the same subject. For example, `rebase` for Foundations is basic usages, whereas Advanced might include `rebase --onto`, `rebase -i --autosquash`, etc.

The change would impact all slides (Advanced for starters), where the tag would be `adavanced/<chapter-name>` rather than just the `<chapter-name>`.

What do you think team?

cc: @brntbeer @matthewmccullough @tlberglund

**Comment by jordanmccullough** [comment]
Pushed an updated to the branch to demonstrate the name spacing idea.

**Comment by matthewmccullough** [comment]
- Love what's here
- I've made Bisect more granular
- I think having more granular slides plays better to our conversational style of teaching
- Perhaps we can both work on adding granularity to this advanced (and the foundations deck)

**Comment by jordanmccullough** [comment]
Following @matthewmccullough's suggestion, followed his changes with additional chapter updates with more granular slides within the chapters. 

FYI: There are still unfinished/draft/TBD slides for some chapters.

@tlberglund and @brntbeer: When you have a chance, would welcome your eyes on this PR and the direction the Advanced deck is taking.

**Comment by brntbeer** [comment]
Going to have time in a few to review! standby

**Comment by tlberglund** [comment]
Working on the mini-summit video today. Should be able to ship it! I'll review these after.

**Comment by matthewmccullough** [comment]
@brntbeer and @tlberglund say they will have time to review so I will happily play third fiddle. Let's ship this.

**Comment by jordanmccullough** [comment]
Fixing the Remotes chapter for Advanced. It's in a bad way right now, and just realized it.

**Comment by tlberglund** [comment]
One small quibble: the GitHub logo in http://localhost:4000/presentations/git-advanced.html#/1/2 (served locally) is the old one. I think this is easier for you to fix, so I'll let you have at it. :)

**Comment by jordanmccullough** [comment]
@tlberglund That'll fall into a different PR with the slide "bumpers" update. This is only the addition of start Advanced slide chapters.

That is, unless I totally mod-ed the bumpers. Need to look if that is the case.

**Comment by tlberglund** [comment]
Then I am happy. I have not combed over it as thoroughly as I'll be able to the next time I prep for a class, but it looks good in the overview I gave it. I'd feel dandy if you :ship:'d it.

**Comment by jordanmccullough** [comment]
Noticed a missing `/` in the Remote refspec chapter slide. Fixed now.

Merging now for initial consumption.

**Pull request merged**
