### PR TITLE
Pages training materials

### PR DESCRIPTION
**Pull request by benbalter**
This pull request is the pull request formally known as #111 before I went ahead and :boom:  the internet. It was based on initial discussion and feedback in #70, with significant awesomification (:tm:) by @matthewmccullough.

Punch list:
- [x] Certain slides falling off small screens (@jordanmccullough, halp?)
- [x] @matthewmccullough's has unmerged edits on the last ~10 slides (I think?)
- [ ] Screencastin' && v/o'n

### CODE REVIEW

**Comment by jordanmccullough** [comment]
@benbalter Can you point me to which slides/content is falling off screen or needs some attention? I'm free this afternoon and would :heart: to get this PR tidied and :ship: (or at least any dependency on me wrapped up).

**Comment by benbalter** [comment]
On a 13" screen, this is what I see:
- http://ben.balter.com/teach.github.com/presentations/github-pages-jekyll-you.html#/6/3

Screen Shot 2013-04-16 at 4 56 45 PM
- http://ben.balter.com/teach.github.com/presentations/github-pages-jekyll-you.html#/8/2

Screen Shot 2013-04-16 at 4 57 02 PM

**Comment by jordanmccullough** [comment]
Thanks for the screenshots. That's super helpful.

A) We can break the content into additional slides
or
B) Use ImpressJS to scale larger-content slides.

Will see what I can do this afternoon. PR for ImpressJS nearly ready for all teach.github.com content.

**Comment by matthewmccullough** [comment]
I'm going to cherry-pick in my final content tweaks after this gets merged. I'll just keep an eye out for this to merge and it all to be back at the teach repo, and then I'll take action and also screencast it.

**Comment by benbalter** [comment]
> We can break the content into additional slides

c91f5e2 fixes.

**Pull request merged**
