### PR TITLE
Usecases for work

### PR DESCRIPTION
**Pull request by virtualandy**
Based on the writeup I was doing in a gist about [using git instead of svn](https://gist.github.com/3725230).

Basic idea is I got some questions about "why switch to git" at work and would love to see a sort of boilerplate list of reasons and resources for making the switch. 

Also, not sure I issued/created this pull request right. Will be glad to fix as it's my first one.

### CODE REVIEW

**Comment by razic** [comment]
:thumbsup:

**Comment by tlberglund** [comment]
Thanks for contributing, Andy!

**Comment by virtualandy** [comment]
Thanks for letting me take part. Please edit/correct/reinforce anything I said in here. There's a few typo's/broken links I have to fix still, too.

**Comment by matthewmccullough** [comment]
I did the first pass of wordsmithing on 4398a76.  More to follow soonish.

This is an excellent contribution Andy!

**Comment by virtualandy** [comment]
I fixed one thing that I had forgotten (an actual link to Git's COPYING file) and a couple other minor typo changes. Do I need to issue a new pull request or can you work your magic to get that in there?

**Comment by matthewmccullough** [comment]
PR would give you credit, but if you do line level comments (even on a closed PR), that would be enough for me to doctor it.  Just go to the commit that brought in the change and then go to the file with the typo and then click on the comment bubble in the line level margin.  Line level comments for the win!

**Comment by virtualandy** [comment]
OK, I think I did that right...if so I'll fix the others. If not excuse the Sat morning brain fog. ;)

**Comment by matthewmccullough** [comment]
@virtualandy Indeed correct.  Hit up the others the same way. :smile:

**Pull request merged**
