### PR TITLE
Advanced slide refinements

### PR DESCRIPTION
**Pull request by jordanmccullough**
This is currently a ~~**WIP** until further notice~~ ready for review. Team contributions are welcome.

### CODE REVIEW

**Comment by jordanmccullough** [comment]
If @github/training-team would lend a quick glance, this polishes up a lot of the very rough-draft slides that are currently in-the-wild for the Advanced deck.

There's still plenty of room for improvement, but I think this is a good ~~first~~ second step at getting the content out to the public.

**Comment by brntbeer** [comment]
On bundle, i was wondering if we could have a section that was  "reasons for bundling"

This may be helpful to think about when doing most of these commands. i currently don't know of a reason to use bundle otherwise. (sure i could look it up, and this is for presentations, so the presenter could mention things). Just a thought!

**Comment by brntbeer** [comment]
screen shot 2013-05-17 at 4 17 13 pm
Two things about this screenshot. 

1) I was wondering if Collaboration and The GitHub Way could be next to each other in ordering?
2) Could the sections of The GitHub Way not keep saying "The Git Way"? seems disconnected?

Noticed git's index is still missing too, but im sure you've noticed!

screen shot 2013-05-17 at 4 15 04 pm

**Comment by jordanmccullough** [comment]
@brntbeer Great observations. Thanks for the helpful screenshot.
1. The order was jus alphabetical for now, we can definitely re-order the slide deck chapters as needed.
2. Totally missed the crazy title repeats. These individual slides certainly need distinct naming.

Updates forthcoming.

**Comment by jordanmccullough** [comment]
Still working on building out _Owning the Index_ slide content. Not struggling with content, but suggestions on a richer description of what's covered in the Foundations content are welcome.

**Comment by brntbeer** [comment]
Not sure what the goal of `Owning the Index` is so i don't know how to suggest anything!

thanks for the changes to 'The GitHub way' sections =)

**Comment by jordanmccullough** [comment]
@brntbeer: Good point. I had some ideas, but now that I review, I think most have been tackled in the Foundations deck. Doing away with this chapter for now and making this PR ready for for :ship:ing.

**Comment by brntbeer** [comment]
Noticed commits come in after you said it was good for shipping. Should i run through things again now to decide if it's ready to go?

**Comment by jordanmccullough** [comment]
@brntbeer Sharp eye! Thanks.

Happened to notice two command typos on the Remote Tracking slides, and a duplication of an example for Branches. Those are the changes you must've seen.

I'm all done here. You shouldn't need to re-review the entire deck, but if you feel the need, I'm sure there's something that could still be polish. However, there aren't any remaining, glaring issues with this PR.

As we're all crunched for time, I'd say we :ship: as is, and can correct later if necessary.

**Pull request merged**
