### PR TITLE
Fix standardization scripts

### PR DESCRIPTION
**Pull request by brntbeer**
## Simplify the process for everyone

Let's narrow this down to two commands whenever anyone wants to join this project.
- `script/setup` is for first time joiners, 
  - it basically is `script/bootstrap` but it would contain any initialization for the project outside of the Ruby (or other) environment.
- `script/server` 
  - runs `script/update` (which runs bootstrap) to contain all of the things that need to happen when you jump back into a project and need to make sure it's up to date. for teach.github.com, this is mostly trivial but habit forming.
  - Also launches the server with acceptance of additional flags.

### CODE REVIEW

**Comment by jordanmccullough** [comment]
Reviewing :soon: with any feedback (if necessary).

**Comment by brntbeer** [comment]
Will update this so it can be merged automatically shortly.

**Comment by brntbeer** [comment]
ping @github/training-team for a :+1:

**Comment by tlberglund** [comment]
Looks sensible to me. :ship: this joint.

**Pull request merged**
